[package]
org = "wso2"
name = "frontend"
version = "0.1.0"
distribution = "2201.2.3"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "asithan"
name = "gcp.demo.client.stubs"
version = "0.1.0"

[[dependency]]
org = "asithan"
name = "gcp.demo.money"
version = "0.1.0"
