[package]
org = "wso2"
name = "email"
version = "0.1.0"
distribution = "2201.2.3"

[build-options]
observabilityIncluded = true
cloud = "k8s"

[[dependency]]
org = "wso2"
name = "gcp.client.stub"
version = "0.1.0"
repository = "local"