version: '3.1'

services:
  jaeger:
    image: jaegertracing/opentelemetry-all-in-one:latest
    ports:
      - 16686:16686
      - 13133:13133
      - 55680:55680
  ads:
    image: wso2inc/ads-service:v0.1.0
  cart:
    image: wso2inc/cart-service:v0.1.0 #add redis
  checkout:
    image: wso2inc/checkout-service:v0.1.0
    environment:
      BAL_CONFIG_DATA: catalogHost="catalog" \n cartHost="cart" \n currencyHost="currency" \n shippingHost="shipping" \n paymentHost="payment" \n emailHost="email" catalogTimeout=3.0 \n cartTimeout=3.0 \n currencyTimeout=3.0 \n shippingTimeout=3.0 \n paymentTimeout=3.0 \n emailTimeout=3.0
    links:
      - catalog
      - cart
      - currency
      - shipping
      - payment
      - email
    depends_on:
      - catalog
      - cart
      - currency
      - shipping
      - payment
      - email
  currency:
    image: wso2inc/currency-service:v0.1.0
  email:
    image: wso2inc/email-service:v0.1.0
    secrets:
      - source: email_config  
        target: /home/ballerina/Config.toml
  frontend:
    image: wso2inc/frontend-service:v0.1.0
    environment:
      BAL_CONFIG_DATA: catalogHost="catalog" \n cartHost="cart" \n recommendHost="recommendation" \n currencyHost="currency" \n shippingHost="shipping" \n checkoutHost="checkout" \n adHost="ads" currencyTimeout=3.0 \n catalogTimeout=3.0 \n cartTimeout=3.0 \n shippingTimeout=3.0 \n recommendationTimeout=3.0 \n adTimeout=3.0 \n checkoutTimeout=3.0 \n  \n [ballerina.observe] \n tracingEnabled=true \n tracingProvider="jaeger" \n [ballerinax.jaeger] \n agentHostname="jaeger" \n agentPort=55680 \n samplerType="const" \n samplerParam=1.0 \n reporterFlushInterval=2000 \n reporterBufferSize=1000
    ports:
      - 9098:9098
    links:
      - catalog
      - cart
      - recommendation
      - currency
      - shipping
      - checkout
      - ads
      - jaeger
    depends_on:
      - catalog
      - cart
      - recommendation
      - currency
      - shipping
      - checkout
      - ads
      - jaeger
  payment:
    image: wso2inc/payment-service:v0.1.0
  catalog:
    image: wso2inc/catalog-service:v0.1.0
    links:
      - jaeger
    depends_on:
      - jaeger
    environment:
      BAL_CONFIG_DATA: \n [ballerina.observe] \n tracingEnabled=true \n tracingProvider="jaeger" \n \n [ballerinax.jaeger] \n agentHostname="jaeger" \n agentPort=55680 \n samplerType="const" \n samplerParam=1.0 \n reporterFlushInterval=2000 \n reporterBufferSize=1000
  recommendation:
    image: wso2inc/recommendation-service:v0.1.0
    environment:
      BAL_CONFIG_DATA: catalogHost="catalog"
    links:
      - catalog
    depends_on:
      - catalog
  shipping:
    image: wso2inc/shipping-service:v0.1.0
secrets:
    email_config:
      file: ./email/Config.toml
