apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-deployment
spec:
  template:
    spec:
      containers:
        - name: email-deployment
          env:
            - name: BAL_CONFIG_FILES
              value: "/home/ballerina/conf/Config.toml:"
