[container.image]
name="email-service"
repository="wso2inc"
tag="v0.1.0"

[[container.copy.files]]
sourceFile="./Config.toml"
target="/home/ballerina/Config.toml"

[cloud.deployment]
internal_domain_name="email-service"
