catalogHost="catalog-service"
cartHost="cart-service"
recommendHost="recommendation-service"
currencyHost="currency-service"
shippingHost="shipping-service"
checkoutHost="checkout-service"
adHost="ads-service"
currencyTimeout=3
catalogTimeout=3
cartTimeout=3
shippingTimeout=3
recommendationTimeout=3
adTimeout=3
checkoutTimeout=3
