catalogHost="catalog-service" 
cartHost="cart-service" 
recommendHost="recommendation-service" 
currencyHost="currency-service" 
shippingHost="shipping-service" 
checkoutHost="checkout-service" 
adHost="ads-service"
