catalogHost="catalog-service" 
cartHost="cart-service" 
currencyHost="currency-service" 
shippingHost="shipping-service" 
paymentHost="payment-service" 
emailHost="email-service"
cartTimeout=3
catalogTimeout=3
currencyTimeout=3
shippingTimeout=3
paymentTimeout=3
emailTimeout=3