---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "frontend"
  name: "frontend-service"
spec:
  ports:
  - name: "port-1-frontend"
    port: 9098
    protocol: "TCP"
    targetPort: 9098
  selector:
    app: "frontend"
  type: "ClusterIP"
---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "front-config-map"
data:
  Config.toml: "catalogUrl=\"catalog-service\" \ncartUrl=\"cart-service\" \nrecommandUrl=\"\
    recommendation-service\" \ncurrencyUrl=\"currency-service\" \nshippingUrl=\"shipping-service\"\
    \ \ncheckoutUrl=\"checkout-service\" \nadUrl=\"ads-service\""
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "frontend"
  name: "frontend-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "frontend"
  template:
    metadata:
      labels:
        app: "frontend"
    spec:
      containers:
      - env:
        - name: "BAL_CONFIG_FILES"
          value: "/home/ballerina/conf/Config.toml:"
        image: "wso2inc/frontend-service:v0.1.0"
        lifecycle:
          preStop:
            exec:
              command:
              - "sleep"
              - "15"
        name: "frontend-deployment"
        ports:
        - containerPort: 9098
          name: "port-1-frontend"
          protocol: "TCP"
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "100Mi"
            cpu: "200m"
        volumeMounts:
        - mountPath: "/home/ballerina/conf/"
          name: "front-config-map-volume"
          readOnly: false
      nodeSelector: {}
      volumes:
      - configMap:
          name: "front-config-map"
        name: "front-config-map-volume"
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  labels:
    app: "frontend"
  name: "frontend-hpa"
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: "apps/v1"
    kind: "Deployment"
    name: "frontend-deployment"
  targetCPUUtilizationPercentage: 50
