---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "recommendation"
  name: "recommendation-service"
spec:
  ports:
  - name: "port-1-recommen"
    port: 9090
    protocol: "TCP"
    targetPort: 9090
  selector:
    app: "recommendation"
  type: "ClusterIP"
---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "rec-config-map"
data:
  Config.toml: "catalogUrl=\"catalog-service\""
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "recommendation"
  name: "recommendation-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "recommendation"
  template:
    metadata:
      labels:
        app: "recommendation"
    spec:
      containers:
      - env:
        - name: "BAL_CONFIG_FILES"
          value: "/home/ballerina/conf/Config.toml:"
        image: "wso2inc/recommendation-service:v0.1.0"
        lifecycle:
          preStop:
            exec:
              command:
              - "sleep"
              - "15"
        name: "recommendation-deployment"
        ports:
        - containerPort: 9090
          name: "port-1-recommen"
          protocol: "TCP"
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "100Mi"
            cpu: "200m"
        volumeMounts:
        - mountPath: "/home/ballerina/conf/"
          name: "rec-config-map-volume"
          readOnly: false
      nodeSelector: {}
      volumes:
      - configMap:
          name: "rec-config-map"
        name: "rec-config-map-volume"
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  labels:
    app: "recommendation"
  name: "recommendation"
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: "apps/v1"
    kind: "Deployment"
    name: "recommendation-deployment"
  targetCPUUtilizationPercentage: 50
