---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "shipping"
  name: "shipping-service"
spec:
  ports:
  - name: "port-1-shipping"
    port: 9095
    protocol: "TCP"
    targetPort: 9095
  selector:
    app: "shipping"
  type: "ClusterIP"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "shipping"
  name: "shipping-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "shipping"
  template:
    metadata:
      labels:
        app: "shipping"
    spec:
      containers:
      - image: "wso2inc/shipping-service:v0.1.0"
        lifecycle:
          preStop:
            exec:
              command:
              - "sleep"
              - "15"
        name: "shipping-deployment"
        ports:
        - containerPort: 9095
          name: "port-1-shipping"
          protocol: "TCP"
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "100Mi"
            cpu: "200m"
      nodeSelector: {}
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  labels:
    app: "shipping"
  name: "shipping-hpa"
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: "apps/v1"
    kind: "Deployment"
    name: "shipping-deployment"
  targetCPUUtilizationPercentage: 50
