[ballerina.observe]
tracingEnabled=true
tracingProvider="jaeger"

[ballerinax.jaeger]
agentHostname="jaeger"
agentPort=55680
samplerType="const"
samplerParam=1.0
reporterFlushInterval=2000
reporterBufferSize=1000

[gmailConfig]
refreshToken = "1//045hYNhzEoCnCCgYIARAAGAQSNwF-L9IrCm-7bv91b7B0y9Bfdqt8kXZTI76mG5hbrK1znpZuv_j1V25u8rgjSfGXcklPVPSHpbU"
clientId = "500615519018-p0npicla2etepirpfsu0628q0b7cvnet.apps.googleusercontent.com"
clientSecret =  "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"
