name: GCP Microservice Build

on:
  pull_request:
  push:
    branches-ignore:
      - master

jobs:
  build:
    if: github.repository_owner == 'ballerina-guides'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: [ads, cart, checkout, currency, email, frontend, payment, productcatalog, recommendation, shipping]
    env:
      TEST_NAME: "${{ matrix.test }}"
    steps:
    - uses: actions/checkout@v2
    - name: Write Test Name to outputs
      id: testname
      run: |
        echo "::set-output name=test-name::${TEST_NAME}"

    - name: Build module using Ballerina zip
      env:
        WORKING_DIR: "gcp.client.stub"
      run: |
        cd ..
        wget https://github.com/ballerina-platform/ballerina-distribution/releases/download/v2201.2.3/ballerina-2201.2.3-swan-lake.zip
        unzip ballerina-2201.2.3-swan-lake.zip
        cd client.stub
        ../ballerina-2201.2.3-swan-lake/bin/bal pack
        ../ballerina-2201.2.3-swan-lake/bin/bal push --repository=local
        cd ${{ steps.testname.outputs.test-name }}
        ../ballerina-2201.2.3-swan-lake/bin/bal build --cloud=k8s

